### ISSUE TITLE
Add white border around QR code to make scanning easier

### ISSUE THREAD

**Issue by JukeboxRhino** [djseeds/lncast#17]
Scanning the invoice QR code is very difficult currently. Adding a white border around the QR will make it easier for apps to scan the invoice.

**Comment by djseeds** [comment]
Thanks for submitting this! I totally agree, this is a must.

**Comment by djseeds** [comment]
Hi @JukeboxRhino, I've added a light card around each QR code. Would you mind trying it out and letting me know if it's any better?

**Comment by djseeds** [comment]
Closing this, as it is now working on my eclair wallet.
