### ISSUE TITLE
Can't find a path from... mainnet

### ISSUE THREAD

**Issue by dolebas** [djseeds/lncast#26]
Installed the Eclair android app and funded a couple of lightning channels. None of them would let me listen to these podcasts tho, error says "can't find a path".

Would be awesome to see this app on mainnet =)

**Comment by dolebas** [comment]
Hey @djseeds thanks for letting me know. Subscribing to this issue to stay updated, looking forward to the mainnet release!

**Comment by djseeds** [comment]
Hey @dolebas, sorry for taking so long, but the testnet site is back up now. Care to try it out and let me know if you have any luck?

**Comment by djseeds** [comment]
Since I wiped the node, it’s not connected to the network at all yet. You may need to open a channel directly to the lncast node

**Comment by dolebas** [comment]
Failed to open channel, error 02

03f32fb41811fac58d15156061437348634ea301b641e07c316064e16959f29b13@lncast.com

**Comment by djseeds** [comment]
Interesting, I'm not familiar with the Eclair errors, so I'll have to charge up my Android phone and try it out. Thanks for trying!

**Comment by dolebas** [comment]
Not sure about the Eclair errors either, hope you will figure it out, and feel free to reach out if you get stuck anywhere!

The one click purchase ux enabled by the android wallet is surprisingly good when everything clicks, but the error reporting have some room for improvement.

**Comment by dolebas** [comment]
Works like a charm via my existing acinq channel. Podcast even starts playing in the background on ff while Eclair is displaying the receipt.

FeelsLikeTheFuture!

**Comment by dolebas** [comment]
Welcome! Will you give me a heads up when its live on mainnet as well?

Looking forward to pioneering one of the first real world implementations of lightning that intelligently captures the value and scalability of micropayments!

**Comment by djseeds** [comment]
Thanks, very flattering!
I'll track mainnet in #27. I'm going to be traveling for the next month, though, so it might be a while.
