### ISSUE TITLE
SSL Cert Doesn't match

### ISSUE THREAD

**Issue by jlopp** [djseeds/lncast#32]
Looks like lncast.com needs an updated ssl cert

**Comment by jlopp** [comment]
Scratch that, it's not an expiration issue. The problem is that the cert is for btcpay.lncast.com and thus it doesn't match lncast.com

**Comment by djseeds** [comment]
Thanks Jameson, quick catch. 😄
I was in the process of transferring the mainnet version from btcpay.lncast.com-> lncast.com and had to wait for DNS to update before fixing the cert. Would you mind verifying that you see a good cert now?

**Comment by jlopp** [comment]
Looks good :+1:
